Repository divyansh-2005/FinNews, pull requests merged in 2024-10, with the labels that each got.

#9 added my feed section
  frontend/src/App.js
  frontend/src/components/Header/Header.jsx
  frontend/src/components/MyFeedSecion/MyFeed.css
  frontend/src/components/MyFeedSecion/MyFeed.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#34 added blogs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Blogs/BlogPageTemplate.css
  frontend/src/components/Blogs/BlogPageTemplate.jsx
  frontend/src/components/Blogs/BlogSection.css
  frontend/src/components/Blogs/BlogSection.jsx
  frontend/src/components/Blogs/BlogsData.json
  frontend/src/components/Blogs/Images/blog-tempate-bg.png
  frontend/src/components/Blogs/Images/brc-bordered-logo.png
  frontend/src/components/Blogs/Images/landingpgimg.png
  frontend/src/components/Header/Header.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#32 Added navigation link to the home page and changed a tags to Link fro…
  frontend/package-lock.json
  frontend/src/components/Header/Header.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#37 resolved navbar fix issue
  frontend/src/components/Header/Header.module.css
  frontend/src/components/Herosection/Herosection.css
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#33 CHORE:added the content and updated the stylings too
  frontend/src/components/All-latest-finiancial-updates/Finiance.jsx
  frontend/src/components/All-latest-finiancial-updates/Finiance.module.css
  frontend/src/components/Daily-NewsLetter/DailyNews.jsx
  frontend/src/components/Daily-NewsLetter/DailyNews.module.css
  frontend/src/components/New-Government-Schemes/GovSchemes.css
  frontend/src/components/New-Government-Schemes/GovSchemes.jsx
  frontend/src/components/StartUp-Insights/StartUp.css
  frontend/src/components/StartUp-Insights/StartUp.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#47 Updated financial updates section and section heading styles and stru…
  frontend/src/components/All-latest-finiancial-updates/Finiance.jsx
  frontend/src/components/All-latest-finiancial-updates/Finiance.module.css
  frontend/src/components/SectionHeading/SectionHeading.css
  frontend/src/components/SectionHeading/SectionHeading.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#46 Added dynamic containt to website home page
  backend/controllers/DailyNewsLetter.js
  backend/controllers/allLatestFinancialUpdates.js
  backend/controllers/startupInsites.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/routes.js
  backend/routes/userRoutes.js
  frontend/public/favicon.ico
  frontend/src/common/CommonBackendEndpoints.jsx
  frontend/src/components/All-latest-finiancial-updates/Finiance.jsx
  frontend/src/components/All-latest-finiancial-updates/Finiance.module.css
  frontend/src/components/Daily-NewsLetter/DailyNews.jsx
  frontend/src/components/Daily-NewsLetter/DailyNews.module.css
  frontend/src/components/New-Government-Schemes/GovSchemes.css
  frontend/src/components/New-Government-Schemes/GovSchemes.jsx
  frontend/src/components/StartUp-Insights/StartUp.css
  frontend/src/components/StartUp-Insights/StartUp.jsx
  frontend/src/pages/Home.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#49 [BUG] #8 Replaced new favicon icon relevent to project containt
  frontend/public/favicon.ico
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#54 feat : Enhanced Navbar UI with proper Palette
  backend/package-lock.json
  frontend/public/index.html
  frontend/public/search.png
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/Header.module.css
  frontend/src/components/Herosection/Herosection.css
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#71 added-contributing.md
  CONTRIBUTING.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#73 Improvement in the ui of my feed section
  backend/package-lock.json
  frontend/src/components/MyFeedSecion/MyFeed.css
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#75 FIX #62 improve toggling of sidebar
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/Header.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#79 Removed side scroll bar
  frontend/src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#121 added newslettersection
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Newsletter/Newsletter.css
  frontend/src/components/Newsletter/Newsletter.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#57 Redesign the government scheme
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/nationalBefinifitScheme.png
  frontend/src/components/New-Government-Schemes/GovSchemes.css
  frontend/src/components/New-Government-Schemes/GovSchemes.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#103 back button added : back button added succesfully at blogs page #74 done
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Blogs/BlogPageTemplate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#142 fix: uniform image sizes, truncate text, and update date format in fi…
  frontend/src/components/All-latest-finiancial-updates/Finiance.jsx
  frontend/src/components/All-latest-finiancial-updates/Finiance.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#145 Adding Login-Signup Feature
  frontend/src/App.js
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Login/Login.jsx
  frontend/src/components/Login/Login.module.css
  frontend/src/components/SignUp/Signup.jsx
  frontend/src/components/SignUp/Signup.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#150 Basic UI Improvements in Hero and My-Feed Section
  frontend/package-lock.json
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/Header.module.css
  frontend/src/components/Herosection/Herosection.css
  frontend/src/components/MyFeedSecion/MyFeed.css
  frontend/src/components/MyFeedSecion/MyFeed.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#160 Added animated back to top button
  frontend/src/App.js
  frontend/src/components/Back-to-top/BackToTop.jsx
  frontend/src/components/Back-to-top/backToTop.css
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#157 added new favicon
  frontend/public/favicon.ico
Labels: gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#155 Changed the static icons to dynamic react icons
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/Footer.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#165 Added Working scroll down button
  frontend/src/components/Herosection/Herosection.css
  frontend/src/components/Herosection/Herosection.jsx
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level 2

#166 make news page responsive
  frontend/src/components/All-latest-finiancial-updates/Finiance.module.css
  frontend/src/components/Daily-NewsLetter/DailyNews.module.css
  frontend/src/components/Header/Header.module.css
  frontend/src/components/Herosection/Herosection.css
  frontend/src/components/New-Government-Schemes/GovSchemes.css
  frontend/src/components/SectionHeading/SectionHeading.css
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#167 added sigin-signup
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Login/Login.jsx
  frontend/src/components/Login/Login.module.css
  frontend/src/components/SignUp/Signup.jsx
  frontend/src/components/SignUp/Signup.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#170 Designed, added collapsible FAQ Modal to Footer
  frontend/src/components/Footer/FAQModal.jsx
  frontend/src/components/Footer/FAQModal.module.css
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/Footer.module.css
Labels: gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#171 [FEAT] : Add Multi-Lingual Support to FinNews
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/GoogleTranslate.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#173 About and Contact Page added
  frontend/src/App.js
  frontend/src/components/Footer/About.jsx
  frontend/src/components/Footer/Contact.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/Footer.module.css
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level 2

#182 search feature in blogs section added
  frontend/src/components/Blogs/BlogSection.css
  frontend/src/components/Blogs/BlogSection.jsx
  frontend/src/components/Blogs/BlogsData.json
Labels: gssoc-ext, hacktoberfest-accepted, level 3, hacktoberfest

#184 Added a fully functional blog page with backend
  backend/controllers/blogController.js
  backend/index.js
  backend/models/blog.js
  backend/routes/routes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Blogs/BlogPageCards.css
  frontend/src/components/Blogs/BlogPageCards.jsx
  frontend/src/components/Blogs/BlogSection.jsx
  frontend/src/components/Blogs/CreateBlog.css
  frontend/src/components/Blogs/CreateBlog.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#189 added featured in table in main readme.md file
  frontend/README.md
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level 2

#193 search feature in My Feeds section added
  frontend/src/components/MyFeedSecion/MyFeed.css
  frontend/src/components/MyFeedSecion/MyFeed.jsx
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level 2

#196 Images for New Goverment Schemes Added
  frontend/package-lock.json
  frontend/src/assets/IndiraGandhi.jpeg
  frontend/src/assets/aamadmi.png
  frontend/src/assets/pension.jpeg
  frontend/src/assets/shravan.png
  frontend/src/assets/snajaygandhi.jpeg
  frontend/src/components/Footer/FAQModal.jsx
  frontend/src/components/New-Government-Schemes/GovSchemes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level 2
